version: '3.8'

services:
  web:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/live_trains_uk
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - DEPARTURE_BOARD_API_KEY=${DEPARTURE_BOARD_API_KEY}
      - SERVICE_DETAILS_API_KEY=${SERVICE_DETAILS_API_KEY}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_TRUST_HOST=${AUTH_TRUST_HOST}
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=live_trains_uk
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
