const stations = {
  'abbey wood': 'ABW',
  aber: 'ABE',
  abercynon: 'ACY',
  aberdare: 'ABA',
  aberdeen: 'ABD',
  aberdour: 'AUR',
  aberdovey: 'AVY',
  abererch: 'ABH',
  abergavenny: 'AGV',
  'abergele & pensarn': 'AGL',
  aberystwyth: 'AYW',
  accrington: 'ACR',
  achanalt: 'AAT',
  achnasheen: 'ACN',
  achnashellach: 'ACH',
  acklington: 'ACK',
  acle: 'ACL',
  'acocks green': 'ACG',
  'acton bridge': 'ACB',
  'acton central': 'ACC',
  'acton main line': 'AML',
  'adderley park': 'ADD',
  addiewell: 'ADW',
  addlestone: 'ASN',
  adisham: 'ADM',
  'adlington (cheshire)': 'ADC',
  'adlington (lancashire)': 'ADL',
  adwick: 'AWK',
  aigburth: 'AIG',
  ainsdale: 'ANS',
  aintree: 'AIN',
  airbles: 'AIR',
  airdrie: 'ADR',
  'albany park': 'AYP',
  albrighton: 'ALB',
  'alderley edge': 'ALD',
  aldermaston: 'AMT',
  aldershot: 'AHT',
  aldrington: 'AGT',
  'alexandra palace': 'AAP',
  'alexandra parade': 'AXP',
  alexandria: 'ALX',
  alfreton: 'ALF',
  'allens west': 'ALW',
  alloa: 'ALO',
  alness: 'ASS',
  alnmouth: 'ALM',
  alresford: 'ALR',
  alsager: 'ASG',
  althorne: 'ALN',
  althorpe: 'ALP',
  altnabreac: 'ABC',
  alton: 'AON',
  altrincham: 'ALT',
  alvechurch: 'ALV',
  ambergate: 'AMB',
  amberley: 'AMY',
  amersham: 'AMR',
  ammanford: 'AMF',
  ancaster: 'ANC',
  anderston: 'AND',
  andover: 'ADV',
  anerley: 'ANZ',
  angmering: 'ANG',
  annan: 'ANN',
  anniesland: 'ANL',
  'ansdell & fairhaven': 'AFV',
  'apperley bridge': 'APY',
  appleby: 'APP',
  'appledore (kent)': 'APD',
  appleford: 'APF',
  'appley bridge': 'APB',
  apsley: 'APS',
  arbroath: 'ARB',
  ardgay: 'ARD',
  ardlui: 'AUI',
  'ardrossan harbour': 'ADS',
  'ardrossan south beach': 'ASB',
  'ardrossan town': 'ADN',
  ardwick: 'ADK',
  'argyle street': 'AGS',
  arisaig: 'ARG',
  arlesey: 'ARL',
  armadale: 'ARM',
  armathwaite: 'AWT',
  arnside: 'ARN',
  arram: 'ARR',
  'arrochar & tarbet': 'ART',
  arundel: 'ARU',
  ascot: 'ACT',
  'ascott-under-wychwood': 'AUW',
  ash: 'ASH',
  'ash vale': 'AHV',
  ashburys: 'ABY',
  'ashchurch for tewkesbury': 'ASC',
  ashfield: 'ASF',
  'ashford international': 'AFK',
  'ashford surrey': 'AFS',
  ashington: 'ASL',
  ashley: 'ASY',
  'ashley down': 'ASD',
  ashtead: 'AHD',
  'ashton-under-lyne': 'AHN',
  'ashurst kent': 'AHS',
  'ashurst new forest': 'ANF',
  'ashwell & morden': 'AWM',
  askam: 'ASK',
  aslockton: 'ALK',
  aspatria: 'ASP',
  'aspley guise': 'APG',
  aston: 'AST',
  atherstone: 'ATH',
  atherton: 'ATN',
  attadale: 'ATT',
  attenborough: 'ATB',
  attleborough: 'ATL',
  auchinleck: 'AUK',
  'audley end': 'AUD',
  'aughton park': 'AUG',
  aviemore: 'AVM',
  avoncliff: 'AVF',
  avonmouth: 'AVN',
  axminster: 'AXM',
  aylesbury: 'AYS',
  'aylesbury vale parkway': 'AVP',
  aylesford: 'AYL',
  aylesham: 'AYH',
  ayr: 'AYR',
  bache: 'BAC',
  baglan: 'BAJ',
  bagshot: 'BAG',
  baildon: 'BLD',
  baillieston: 'BIO',
  balcombe: 'BAB',
  baldock: 'BDK',
  balham: 'BAL',
  'balloch central': 'BHC',
  balmossie: 'BSI',
  'bamber bridge': 'BMB',
  bamford: 'BAM',
  banavie: 'BNV',
  banbury: 'BAN',
  'bangor (gwynedd)': 'BNG',
  'bank hall': 'BAH',
  banstead: 'BAD',
  barassie: 'BSS',
  'bardon mill': 'BLL',
  'bare lane': 'BAR',
  bargeddie: 'BGI',
  bargoed: 'BGD',
  barking: 'BKG',
  'barking riverside': 'BGV',
  barlaston: 'BRT',
  barming: 'BMG',
  barmouth: 'BRM',
  barnehurst: 'BNH',
  'barnes bridge': 'BNI',
  barnes: 'BNS',
  barnetby: 'BTB',
  barnham: 'BAA',
  barnhill: 'BNL',
  barnsley: 'BNY',
  barnstaple: 'BNP',
  'barnt green': 'BTG',
  barrhead: 'BRR',
  barrhill: 'BRL',
  'barrow haven': 'BAV',
  'barrow upon soar': 'BWS',
  'barrow-in-furness': 'BIF',
  'barry docks': 'BYD',
  'barry island': 'BYI',
  'barry links': 'BYL',
  barry: 'BRY',
  'barton-on-humber': 'BAU',
  basildon: 'BSO',
  basingstoke: 'BSK',
  'bat & ball': 'BBL',
  'bath spa': 'BTH',
  bathgate: 'BHG',
  batley: 'BTL',
  battersby: 'BTT',
  'battersea park': 'BAK',
  battle: 'BAT',
  battlesbridge: 'BLB',
  bayford: 'BAY',
  beaconsfield: 'BCF',
  bearley: 'BER',
  bearsden: 'BRN',
  bearsted: 'BSD',
  beasdale: 'BSL',
  'beaulieu road': 'BEU',
  beauly: 'BEL',
  bebington: 'BEB',
  beccles: 'BCC',
  'beckenham hill': 'BEC',
  'beckenham junction': 'BKJ',
  'bedford st johns': 'BSJ',
  bedford: 'BDM',
  bedhampton: 'BDH',
  bedminster: 'BMT',
  bedworth: 'BEH',
  bedwyn: 'BDW',
  beeston: 'BEE',
  bekesbourne: 'BKS',
  'belfast central': 'BFC',
  'belle vue': 'BLV',
  bellgrove: 'BLG',
  bellingham: 'BGM',
  bellshill: 'BLH',
  belmont: 'BLM',
  belper: 'BLP',
  beltring: 'BEG',
  belvedere: 'BVD',
  bempton: 'BEM',
  'ben rhydding': 'BEY',
  benfleet: 'BEF',
  bentham: 'BEN',
  'bentley (hampshire)': 'BTY',
  'bentley (south yorkshire)': 'BYK',
  'bere alston': 'BAS',
  'bere ferrers': 'BFE',
  berkhamsted: 'BKM',
  berkswell: 'BKW',
  'bermuda park': 'BEP',
  'berney arms': 'BYA',
  'berry brow': 'BBW',
  berrylands: 'BRS',
  'berwick (sussex)': 'BRK',
  'berwick-upon-tweed': 'BWK',
  'bescar lane': 'BES',
  'bescot stadium': 'BSC',
  betchworth: 'BTO',
  'bethnal green': 'BET',
  'betws-y-coed': 'BYC',
  beverley: 'BEV',
  bexhill: 'BEX',
  bexley: 'BXY',
  bexleyheath: 'BXH',
  'bicester north': 'BCS',
  'bicester village': 'BIT',
  bickley: 'BKL',
  bidston: 'BID',
  biggleswade: 'BIW',
  bilbrook: 'BBK',
  billericay: 'BIC',
  billingham: 'BIL',
  billingshurst: 'BIG',
  bingham: 'BIN',
  bingley: 'BIY',
  birchgrove: 'BCG',
  'birchington-on-sea': 'BCH',
  birchwood: 'BWD',
  birkbeck: 'BIK',
  birkdale: 'BDL',
  'birkenhead central': 'BKC',
  'birkenhead hamilton square': 'BKQ',
  'birkenhead north': 'BKN',
  'birkenhead park': 'BKP',
  'birmingham international': 'BHI',
  'birmingham moor street': 'BMO',
  'birmingham new street': 'BHM',
  'birmingham snow hill': 'BSW',
  'bishop auckland': 'BIA',
  bishopbriggs: 'BBG',
  'bishops stortford': 'BIS',
  'bishopstone (sussex)': 'BIP',
  bishopton: 'BPT',
  bitterne: 'BTE',
  blackburn: 'BBN',
  blackheath: 'BKH',
  'blackhorse road': 'BHO',
  'blackpool north': 'BPN',
  'blackpool pleasure beach': 'BPB',
  'blackpool south': 'BPS',
  blackridge: 'BKR',
  blackrod: 'BLK',
  blackwater: 'BAW',
  'blaenau ffestiniog': 'BFF',
  'blair atholl': 'BLA',
  blairhill: 'BAI',
  'blake street': 'BKT',
  blakedown: 'BKD',
  blantyre: 'BLT',
  blaydon: 'BLO',
  bleasby: 'BSB',
  bletchley: 'BLY',
  'bloxwich north': 'BWN',
  bloxwich: 'BLX',
  'blundellsands & crosby': 'BLN',
  'blythe bridge': 'BYB',
  'bodmin parkway': 'BOD',
  bodorgan: 'BOR',
  'bognor regis': 'BOG',
  bogston: 'BGS',
  'bond street': 'BDS',
  bolton: 'BON',
  'bolton-on-dearne': 'BTD',
  bookham: 'BKA',
  'bootle (cumbria)': 'BOC',
  'bootle new strand': 'BNW',
  'bootle oriel road': 'BOT',
  bordesley: 'BBS',
  'borough green & wrotham': 'BRG',
  borth: 'BRH',
  bosham: 'BOH',
  boston: 'BSN',
  botley: 'BOE',
  bottesford: 'BTF',
  'bourne end': 'BNE',
  bournemouth: 'BMH',
  bournville: 'BRV',
  'bow brickhill': 'BWB',
  'bow street': 'BOW',
  'bowes park': 'BOP',
  bowling: 'BWG',
  'box hill & westhumble': 'BXW',
  bracknell: 'BCE',
  'bradford forster square': 'BDQ',
  'bradford interchange': 'BDI',
  'bradford-on-avon': 'BOA',
  brading: 'BDN',
  braintree: 'BTR',
  'braintree freeport': 'BTP',
  bramhall: 'BML',
  'bramley (hants)': 'BMY',
  'bramley (west yorkshire)': 'BLE',
  'brampton (cumbria)': 'BMP',
  'brampton (suffolk)': 'BRP',
  branchton: 'BCN',
  brandon: 'BND',
  branksome: 'BSM',
  braystones: 'BYS',
  bredbury: 'BDY',
  breich: 'BRC',
  brentford: 'BFD',
  'brent cross west': 'BCZ',
  brentwood: 'BRE',
  'bricket wood': 'BWO',
  'bridge of allan': 'BEA',
  'bridge of orchy': 'BRO',
  bridgend: 'BGN',
  bridgeton: 'BDG',
  bridgwater: 'BWT',
  bridlington: 'BDT',
  brierfield: 'BRF',
  brigg: 'BGG',
  brighouse: 'BGH',
  brighton: 'BTN',
  brimsdown: 'BMD',
  brinnington: 'BNT',
  'bristol parkway': 'BPW',
  'bristol temple meads': 'BRI',
  brithdir: 'BHD',
  'briton ferry': 'BNF',
  brixton: 'BRX',
  'broad green': 'BGE',
  broadbottom: 'BDB',
  broadstairs: 'BSR',
  brockenhurst: 'BCU',
  brockholes: 'BHS',
  brockley: 'BCY',
  'brockley whins': 'BNR',
  'bromborough rake': 'BMR',
  bromborough: 'BOM',
  'bromley cross': 'BMC',
  'bromley north': 'BMN',
  'bromley south': 'BMS',
  bromsgrove: 'BMV',
  'brondesbury park': 'BSP',
  brondesbury: 'BSY',
  'brookmans park': 'BPK',
  brookwood: 'BKO',
  broome: 'BME',
  broomfleet: 'BMF',
  brora: 'BRA',
  brough: 'BUH',
  'broughty ferry': 'BYF',
  broxbourne: 'BXB',
  'bruce grove': 'BCV',
  'brundall gardens': 'BGA',
  brundall: 'BDA',
  brunstane: 'BSU',
  brunswick: 'BRW',
  bruton: 'BRU',
  bryn: 'BYN',
  buckenham: 'BUC',
  buckley: 'BCK',
  bucknell: 'BUK',
  'buckshaw parkway': 'BSV',
  bugle: 'BGL',
  'builth road': 'BHR',
  bulwell: 'BLW',
  bures: 'BUE',
  'burgess hill': 'BUG',
  'burley park': 'BUY',
  'burley-in-wharfedale': 'BUW',
  burnage: 'BNA',
  burneside: 'BUD',
  burnham: 'BNM',
  'burnham-on-crouch': 'BUU',
  'burnley barracks': 'BUB',
  'burnley central': 'BNC',
  'burnley manchester road': 'BYM',
  burnside: 'BUI',
  burntisland: 'BTS',
  'burscough bridge': 'BCB',
  'burscough junction': 'BCJ',
  bursledon: 'BUO',
  'burton joyce': 'BUJ',
  'burton-on-trent': 'BUT',
  'bury st edmunds': 'BSE',
  busby: 'BUS',
  'bush hill park': 'BHK',
  bushey: 'BSH',
  'butlers lane': 'BUL',
  buxted: 'BXD',
  buxton: 'BUX',
  'byfleet & new haw': 'BFN',
  bynea: 'BYE',
  cadoxton: 'CAD',
  caergwrle: 'CGW',
  caerphilly: 'CPH',
  caersws: 'CWS',
  caldercruix: 'CAC',
  caldicot: 'CDT',
  'caledonian road & barnsbury': 'CIR',
  calstock: 'CSK',
  'cam & dursley': 'CDU',
  camberley: 'CAM',
  camborne: 'CBN',
  cambridge: 'CBG',
  'cambridge heath': 'CBH',
  'cambridge north': 'CMB',
  cambuslang: 'CBL',
  'camden road': 'CMD',
  camelon: 'CMO',
  'cameron bridge': 'CBX',
  'canada water': 'ZCW',
  'canary wharf': 'CWX',
  canley: 'CNL',
  cannock: 'CAO',
  canonbury: 'CNN',
  'canterbury east': 'CBE',
  'canterbury west': 'CBW',
  cantley: 'CNY',
  capenhurst: 'CPU',
  'carbis bay': 'CBB',
  cardenden: 'CDD',
  'cardiff bay': 'CDB',
  'cardiff central': 'CDF',
  'cardiff international airport': 'XCF',
  'cardiff queen street': 'CDQ',
  cardonald: 'CDO',
  cardross: 'CDR',
  carfin: 'CRF',
  cark: 'CAK',
  carlisle: 'CAR',
  carlton: 'CTO',
  carluke: 'CLU',
  carmarthen: 'CMN',
  carmyle: 'CML',
  carnforth: 'CNF',
  carnoustie: 'CAN',
  carntyne: 'CAY',
  'carpenders park': 'CPK',
  carrbridge: 'CAG',
  carshalton: 'CSH',
  'carshalton beeches': 'CSB',
  carstairs: 'CRS',
  cartsdyke: 'CDY',
  'castle bar park': 'CBP',
  'castle cary': 'CLC',
  castleford: 'CFD',
  castleton: 'CAS',
  'castleton moor': 'CSM',
  caterham: 'CAT',
  'catford bridge': 'CFB',
  catford: 'CTF',
  cathays: 'CYS',
  cathcart: 'CCT',
  cattal: 'CTL',
  causeland: 'CAU',
  'cefn-y-bedd': 'CYB',
  'chadwell heath': 'CTH',
  'chafford hundred': 'CFH',
  'chalfont & latimer': 'CFO',
  chalkwell: 'CHW',
  'chandlers ford': 'CFR',
  'chapel-en-le-frith': 'CEF',
  chapeltown: 'CLN',
  chapleton: 'CPN',
  'chappel & wakes colne': 'CWC',
  charing: 'CHG',
  'charing cross (glasgow)': 'CHC',
  charlbury: 'CBY',
  charlton: 'CTN',
  chartham: 'CRT',
  'chassen road': 'CSR',
  chatelherault: 'CTE',
  chatham: 'CTM',
  chathill: 'CHT',
  'cheadle hulme': 'CHU',
  cheam: 'CHE',
  cheddington: 'CED',
  chelford: 'CEL',
  chelmsford: 'CHM',
  chelsfield: 'CLD',
  'cheltenham spa': 'CNM',
  chepstow: 'CPW',
  'cherry tree': 'CYT',
  chertsey: 'CHY',
  cheshunt: 'CHN',
  'chessington north': 'CSN',
  'chessington south': 'CSS',
  chester: 'CTR',
  'chester road': 'CRD',
  chesterfield: 'CHD',
  'chester-le-street': 'CLS',
  'chestfield & swalecliffe': 'CSW',
  chetnole: 'CNO',
  chichester: 'CCH',
  chilham: 'CIL',
  chilworth: 'CHL',
  chingford: 'CHI',
  chinley: 'CLY',
  chippenham: 'CPM',
  chipstead: 'CHP',
  chirk: 'CRK',
  chislehurst: 'CIT',
  chiswick: 'CHK',
  cholsey: 'CHO',
  chorley: 'CRL',
  chorleywood: 'CLW',
  christchurch: 'CHR',
  'christs hospital': 'CHH',
  'church & oswaldtwistle': 'CTW',
  'church fenton': 'CHF',
  'church stretton': 'CTT',
  cilmeri: 'CIM',
  'city thameslink': 'CTK',
  'clacton-on-sea': 'CLT',
  clandon: 'CLA',
  'clapham (north yorkshire)': 'CPY',
  'clapham high street': 'CLP',
  'clapham junction': 'CLJ',
  clapton: 'CPT',
  'clarbeston road': 'CLR',
  clarkston: 'CKS',
  claverdon: 'CLV',
  claygate: 'CLG',
  cleethorpes: 'CLE',
  cleland: 'CEA',
  clifton: 'CLI',
  'clifton down': 'CFN',
  clitheroe: 'CLH',
  'clock house': 'CLK',
  clunderwen: 'CUW',
  clydebank: 'CYK',
  'coatbridge central': 'CBC',
  'coatbridge sunnyside': 'CBS',
  coatdyke: 'COA',
  'cobham & stoke dabernon': 'CSD',
  codsall: 'CSL',
  cogan: 'CGN',
  colchester: 'COL',
  'colchester town': 'CET',
  'coleshill parkway': 'CEH',
  collingham: 'CLM',
  collington: 'CLL',
  colne: 'CNE',
  colwall: 'CWL',
  'colwyn bay': 'CWB',
  combe: 'CME',
  commondale: 'COM',
  congleton: 'CNG',
  conisbrough: 'CNS',
  'connel ferry': 'CON',
  'conon bridge': 'CBD',
  cononley: 'CEY',
  'conway park': 'CNP',
  conwy: 'CNW',
  'cooden beach': 'COB',
  cookham: 'COO',
  cooksbridge: 'CBR',
  coombe: 'COE',
  copplestone: 'COP',
  corbridge: 'CRB',
  corby: 'COR',
  'corfe castle': 'CFC',
  corkerhill: 'CKH',
  corkickle: 'CKL',
  corpach: 'CPA',
  corrour: 'CRR',
  coryton: 'COY',
  coseley: 'CSY',
  cosford: 'COS',
  cosham: 'CSA',
  cottingham: 'CGM',
  cottingley: 'COT',
  'coulsdon south': 'CDS',
  'coulsdon town': 'CDN',
  coventry: 'COV',
  'coventry arena': 'CAA',
  cowden: 'CWN',
  cowdenbeath: 'COW',
  'cradley heath': 'CRA',
  craigendoran: 'CGD',
  cramlington: 'CRM',
  'cranbrook (devon)': 'CBK',
  'craven arms': 'CRV',
  crawley: 'CRW',
  crayford: 'CRY',
  crediton: 'CDI',
  cressing: 'CES',
  cressington: 'CSG',
  creswell: 'CWD',
  crewe: 'CRE',
  crewkerne: 'CKN',
  'crews hill': 'CWH',
  crianlarich: 'CNR',
  criccieth: 'CCC',
  cricklewood: 'CRI',
  croftfoot: 'CFF',
  'crofton park': 'CFT',
  cromer: 'CMR',
  cromford: 'CMF',
  crookston: 'CKT',
  'cross gates': 'CRG',
  crossflatts: 'CFL',
  crosshill: 'COI',
  crosskeys: 'CKY',
  crossmyloof: 'CMY',
  croston: 'CSO',
  'crouch hill': 'CRH',
  crowborough: 'COH',
  crowhurst: 'CWU',
  crowle: 'CWE',
  crowthorne: 'CRN',
  croy: 'CRO',
  'crystal palace': 'CYP',
  cuddington: 'CUD',
  cuffley: 'CUF',
  culham: 'CUM',
  culrain: 'CUA',
  cumbernauld: 'CUB',
  cupar: 'CUP',
  curriehill: 'CUH',
  'custom house': 'CUS',
  cuxton: 'CUX',
  cwmbach: 'CMH',
  cwmbran: 'CWM',
  cynghordy: 'CYN',
  'dagenham dock': 'DDK',
  'dagenham east l.t.': 'ZDE',
  'daisy hill': 'DSY',
  'dalgety bay': 'DAG',
  dalmally: 'DAL',
  dalmarnock: 'DAK',
  dalmeny: 'DAM',
  dalmuir: 'DMR',
  dalreoch: 'DLR',
  dalry: 'DLY',
  'dalston (cumbria)': 'DLS',
  'dalston junction': 'DLJ',
  'dalston kingsland': 'DLK',
  dalton: 'DLT',
  dalwhinnie: 'DLW',
  danby: 'DNY',
  danescourt: 'DCT',
  danzey: 'DZY',
  darlington: 'DAR',
  darnall: 'DAN',
  darsham: 'DSM',
  dartford: 'DFD',
  darton: 'DRT',
  darwen: 'DWN',
  datchet: 'DAT',
  davenport: 'DVN',
  dawlish: 'DWL',
  'dawlish warren': 'DWW',
  deal: 'DEA',
  dean: 'DEN',
  deansgate: 'DGT',
  deganwy: 'DGY',
  deighton: 'DHN',
  delamere: 'DLM',
  'denby dale': 'DBD',
  denham: 'DNM',
  'denham golf club': 'DGC',
  'denmark hill': 'DMK',
  dent: 'DNT',
  denton: 'DTN',
  deptford: 'DEP',
  derby: 'DBY',
  'derby road': 'DBR',
  'dereham market place': 'DEB',
  devonport: 'DPT',
  dewsbury: 'DEW',
  'didcot parkway': 'DID',
  'digby & sowton': 'DIG',
  'dilton marsh': 'DMH',
  'dinas powys': 'DNS',
  'dinas rhondda': 'DMG',
  'dingle road': 'DGL',
  dingwall: 'DIN',
  dinsdale: 'DND',
  dinting: 'DTG',
  disley: 'DSL',
  diss: 'DIS',
  dockyard: 'DOC',
  dodworth: 'DOD',
  dolau: 'DOL',
  doleham: 'DLH',
  dolgarrog: 'DLG',
  dolwyddelan: 'DWD',
  doncaster: 'DON',
  'dorchester south': 'DCH',
  'dorchester west': 'DCW',
  'dore & totley': 'DOR',
  'dorking deepdene': 'DPD',
  dorking: 'DKG',
  'dorking west': 'DKT',
  dormans: 'DMS',
  dorridge: 'DDG',
  'dove holes': 'DVH',
  'dover priory': 'DVP',
  dovercourt: 'DVC',
  'dovey junction': 'DVY',
  'downham market': 'DOW',
  'drayton green': 'DRG',
  'drayton manor': 'DRY',
  'drayton park': 'DYP',
  drem: 'DRM',
  driffield: 'DRF',
  drigg: 'DRI',
  'droitwich spa': 'DTW',
  dronfield: 'DRO',
  drumchapel: 'DMC',
  drumfrochar: 'DFR',
  drumgelloch: 'DRU',
  drumry: 'DMY',
  duddeston: 'DUD',
  'dudley port': 'DDP',
  duffield: 'DFI',
  duirinish: 'DRN',
  'duke street': 'DST',
  dullingham: 'DUL',
  'dumbarton central': 'DBC',
  'dumbarton east': 'DBE',
  dumbreck: 'DUM',
  dumfries: 'DMF',
  'dumpton park': 'DMP',
  dunbar: 'DUN',
  dunblane: 'DBL',
  duncraig: 'DCG',
  dundee: 'DEE',
  'dunfermline queen margaret': 'DFL',
  'dunfermline city': 'DFE',
  'dunkeld & birnam': 'DKD',
  dunlop: 'DNL',
  dunoon: 'DUO',
  'dunrobin castle': 'DNO',
  duns: 'DUU',
  dunston: 'DOT',
  'dunton green': 'DNG',
  durham: 'DHM',
  'durrington-on-sea': 'DUR',
  dyce: 'DYC',
  'dyffryn ardudwy': 'DYF',
  eaglescliffe: 'EAG',
  'ealing broadway': 'EAL',
  'ealing common': 'ZEC',
  earlestown: 'ERL',
  earley: 'EAR',
  "earl's court l.t.": 'ZET',
  earlsfield: 'EAD',
  earlston: 'EAS',
  'earlswood (surrey)': 'ELD',
  'earlswood (west midlands)': 'EWD',
  'east boldon': 'EBL',
  'east cowes': 'ECW',
  'east croydon': 'ECR',
  'east didsbury': 'EDY',
  'east dulwich': 'EDW',
  'east farleigh': 'EFL',
  'east garforth': 'EGF',
  'east grinstead': 'EGR',
  'east kilbride': 'EKL',
  'east linton': 'ELT',
  'east malling': 'EML',
  'east midlands parkway': 'EMD',
  'east tilbury': 'ETL',
  'east worthing': 'EWR',
  eastbourne: 'EBN',
  eastbrook: 'EBK',
  easterhouse: 'EST',
  'eastham rake': 'ERA',
  eastleigh: 'ESL',
  eastrington: 'EGN',
  'ebbsfleet international': 'EBD',
  'ebbw vale parkway': 'EBV',
  'ebbw vale town': 'EBB',
  eccles: 'ECC',
  'eccles road': 'ECS',
  'eccleston park': 'ECL',
  edale: 'EDL',
  'eden park': 'EDN',
  edenbridge: 'EBR',
  'edenbridge town': 'EBT',
  'edge hill': 'EDG',
  'edinburgh gateway': 'EGY',
  'edinburgh park': 'EDP',
  'edinburgh waverley': 'EDB',
  'edmonton green': 'EDR',
  'effingham junction': 'EFF',
  eggesford: 'EGG',
  egham: 'EGH',
  egton: 'EGT',
  'elephant & castle': 'EPH',
  elgin: 'ELG',
  'ellesmere port': 'ELP',
  'elmers end': 'ELE',
  'elmstead woods': 'ESD',
  elmswell: 'ESW',
  elsecar: 'ELR',
  elsenham: 'ESM',
  'elstree & borehamwood': 'ELS',
  eltham: 'ELW',
  'elton & orston': 'ELO',
  ely: 'ELY',
  'emerson park': 'EMP',
  emsworth: 'EMS',
  'energlyn & churchill park': 'ECP',
  'enfield chase': 'ENC',
  'enfield lock': 'ENL',
  'enfield town': 'ENF',
  entwistle: 'ENT',
  'epsom downs': 'EPD',
  epsom: 'EPS',
  erdington: 'ERD',
  eridge: 'ERI',
  erith: 'ERH',
  esher: 'ESH',
  eskbank: 'EKB',
  'essex road': 'EXR',
  etchingham: 'ETC',
  'euxton balshaw lane': 'EBA',
  evesham: 'EVE',
  'ewell east': 'EWE',
  'ewell west': 'EWW',
  'exeter central': 'EXC',
  'exeter st davids': 'EXD',
  'exeter st thomas': 'EXT',
  'exhibition centre': 'EXG',
  exmouth: 'EXM',
  exton: 'EXN',
  eynsford: 'EYN',
  fairbourne: 'FRB',
  fairfield: 'FRF',
  fairlie: 'FRL',
  fairwater: 'FRW',
  falconwood: 'FCN',
  'falkirk grahamston': 'FKG',
  'falkirk high': 'FKK',
  'falls of cruachan': 'FOC',
  falmer: 'FMR',
  'falmouth docks': 'FAL',
  'falmouth town': 'FMT',
  fareham: 'FRM',
  'farnborough main': 'FNB',
  'farnborough north': 'FNN',
  farncombe: 'FNC',
  farnham: 'FNH',
  'farningham road': 'FNR',
  farnworth: 'FNW',
  farringdon: 'ZFD',
  fauldhouse: 'FLD',
  faversham: 'FAV',
  faygate: 'FGT',
  fazakerley: 'FAZ',
  fearn: 'FRN',
  featherstone: 'FEA',
  felixstowe: 'FLX',
  fellgate: 'FEG',
  feltham: 'FEL',
  feniton: 'FNT',
  'fenny stratford': 'FEN',
  fernhill: 'FER',
  ferriby: 'FRY',
  ferryside: 'FYS',
  ffairfach: 'FFA',
  filey: 'FIL',
  'filton abbey wood': 'FIT',
  'finchley road & frognal': 'FNY',
  'finsbury park': 'FPK',
  finstock: 'FIN',
  fishbourne: 'FSB',
  fishersgate: 'FSG',
  'fishguard & goodwick': 'FGW',
  'fishguard harbour': 'FGH',
  fiskerton: 'FSK',
  fitzwilliam: 'FZW',
  'five ways': 'FWY',
  fleet: 'FLE',
  flimby: 'FLM',
  flint: 'FLN',
  flitwick: 'FLT',
  flixton: 'FLI',
  'flowery field': 'FLF',
  'folkestone central': 'FKC',
  'folkestone west': 'FKW',
  ford: 'FOD',
  'forest gate': 'FOG',
  'forest hill': 'FOH',
  formby: 'FBY',
  forres: 'FOR',
  forsinard: 'FRS',
  'fort matilda': 'FTM',
  'fort william': 'FTW',
  'four oaks': 'FOK',
  foxfield: 'FOX',
  foxton: 'FXN',
  frant: 'FRT',
  fratton: 'FTN',
  freshfield: 'FRE',
  freshford: 'FFD',
  frimley: 'FML',
  'frinton-on-sea': 'FRI',
  frizinghall: 'FZH',
  frodsham: 'FRD',
  frome: 'FRO',
  fulwell: 'FLW',
  'furness vale': 'FNV',
  'furze platt': 'FZP',
  'gainsborough central': 'GNB',
  'gainsborough lea road': 'GBL',
  galashiels: 'GAL',
  garelochhead: 'GCH',
  garforth: 'GRF',
  gargrave: 'GGV',
  garrowhill: 'GAR',
  garscadden: 'GRS',
  garsdale: 'GSD',
  garston: 'GSN',
  garswood: 'GSW',
  gartcosh: 'GRH',
  'garth (powys)': 'GTH',
  'garth (mid glamorgan)': 'GMG',
  garve: 'GVE',
  gathurst: 'GST',
  gatley: 'GTY',
  'gatwick airport': 'GTW',
  'georgemas junction': 'GGJ',
  'gerrards cross': 'GER',
  'gidea park': 'GDP',
  giffnock: 'GFN',
  giggleswick: 'GIG',
  gilberdyke: 'GBD',
  'gilfach fargoed': 'GFF',
  'gillingham (dorset)': 'GIL',
  'gillingham (kent)': 'GLM',
  gilshochill: 'GSC',
  'gipsy hill': 'GIP',
  girvan: 'GIR',
  glaisdale: 'GLS',
  'glan conwy': 'GCW',
  'glasgow central': 'GLC',
  'glasgow queen street': 'GLQ',
  glasshoughton: 'GLH',
  glazebrook: 'GLZ',
  gleneagles: 'GLE',
  glenfinnan: 'GLF',
  glengarnock: 'GLG',
  'glenrothes with thornton': 'GLT',
  glossop: 'GLO',
  gloucester: 'GCR',
  glynde: 'GLY',
  gobowen: 'GOB',
  godalming: 'GOD',
  godley: 'GDL',
  godstone: 'GDN',
  goldthorpe: 'GOE',
  'golf street': 'GOF',
  golspie: 'GOL',
  gomshall: 'GOM',
  goodmayes: 'GMY',
  goole: 'GOO',
  goostrey: 'GTR',
  'gordon hill': 'GDH',
  gorebridge: 'GBG',
  'goring & streatley': 'GOR',
  'goring-by-sea': 'GBS',
  gorton: 'GTO',
  'gospel oak': 'GPO',
  gourock: 'GRK',
  'gourock pier': 'GXX',
  gowerton: 'GWN',
  goxhill: 'GOX',
  'grange park': 'GPK',
  'grange-over-sands': 'GOS',
  grangetown: 'GTN',
  grantham: 'GRA',
  grateley: 'GRT',
  'gravelly hill': 'GVH',
  gravesend: 'GRV',
  grays: 'GRY',
  'great ayton': 'GTA',
  'great bentley': 'GRB',
  'great chesterford': 'GRC',
  'great coates': 'GCT',
  'great malvern': 'GMV',
  'great missenden': 'GMN',
  'great yarmouth': 'GYM',
  'green lane': 'GNL',
  'green road': 'GNR',
  greenbank: 'GBK',
  greenfaulds: 'GRL',
  greenfield: 'GNF',
  greenford: 'GFD',
  'greenhithe for bluewater': 'GNH',
  'greenock central': 'GKC',
  'greenock west': 'GKW',
  greenwich: 'GNW',
  'gretna green': 'GEA',
  'grimsby docks': 'GMD',
  'grimsby town': 'GMB',
  grindleford: 'GRN',
  grosmont: 'GMT',
  'grove park': 'GRP',
  'guide bridge': 'GUI',
  guildford: 'GLD',
  guiseley: 'GSY',
  gunnersbury: 'GUN',
  gunnislake: 'GSL',
  gunton: 'GNT',
  gwersyllt: 'GWE',
  'gypsy lane': 'GYP',
  habrough: 'HAB',
  hackbridge: 'HCB',
  'hackney central': 'HKC',
  'hackney downs': 'HAC',
  'hackney wick': 'HKW',
  'haddenham & thame parkway': 'HDM',
  haddiscoe: 'HAD',
  hadfield: 'HDF',
  'hadley wood': 'HDW',
  'hag fold': 'HGF',
  haggerston: 'HGG',
  hagley: 'HAG',
  hairmyres: 'HMY',
  hale: 'HAL',
  halesworth: 'HAS',
  halewood: 'HED',
  halifax: 'HFX',
  'hall green': 'HLG',
  "hall i' th' wood": 'HID',
  'hall road': 'HLR',
  halling: 'HAI',
  haltwhistle: 'HWH',
  'ham street': 'HMT',
  hamble: 'HME',
  'hamilton central': 'HNC',
  'hamilton west': 'HNW',
  hammerton: 'HMM',
  'hampden park': 'HMD',
  'hampstead heath': 'HDH',
  hampton: 'HMP',
  'hampton court': 'HMC',
  'hampton wick': 'HMW',
  'hampton-in-arden': 'HIA',
  hamstead: 'HSD',
  hamworthy: 'HAM',
  hanborough: 'HND',
  handforth: 'HTH',
  hanwell: 'HAN',
  hapton: 'HPN',
  harlech: 'HRL',
  harlesden: 'HDN',
  'harling road': 'HRD',
  harlington: 'HLN',
  'harlow mill': 'HWM',
  'harlow town': 'HWN',
  'harold wood': 'HRO',
  harpenden: 'HPD',
  harrietsham: 'HRM',
  'harringay green lanes': 'HRY',
  harringay: 'HGY',
  harrington: 'HRR',
  harrogate: 'HGT',
  'harrow & wealdstone': 'HRW',
  'harrow-on-the-hill': 'HOH',
  hartford: 'HTF',
  hartlebury: 'HBY',
  hartlepool: 'HPL',
  hartwood: 'HTW',
  'harwich international': 'HPQ',
  'harwich town': 'HWC',
  haslemere: 'HSL',
  hassocks: 'HSK',
  hastings: 'HGS',
  'hatch end': 'HTE',
  hatfield: 'HAT',
  'hatfield & stainforth': 'HFS',
  'hatfield peverel': 'HAP',
  hathersage: 'HSG',
  hattersley: 'HTY',
  hatton: 'HTN',
  havant: 'HAV',
  havenhouse: 'HVN',
  haverfordwest: 'HVF',
  'hawarden bridge': 'HWB',
  hawarden: 'HWD',
  hawick: 'HWK',
  hawkhead: 'HKH',
  'haydon bridge': 'HDB',
  'haydons road': 'HYR',
  'hayes & harlington': 'HAY',
  'hayes (kent)': 'HYS',
  hayle: 'HYL',
  haymarket: 'HYM',
  'haywards heath': 'HHE',
  'hazel grove': 'HAZ',
  'headbolt lane': 'HBL',
  headcorn: 'HCN',
  headingley: 'HDY',
  'headstone lane': 'HDL',
  'heald green': 'HDG',
  healing: 'HLI',
  'heath high level': 'HHL',
  'heath low level': 'HLL',
  'heathrow terminal 4 rail': 'HAF',
  'heathrow terminal 5 rail': 'HWV',
  'heathrow terminals 1-2-3 rail': 'HXX',
  'heaton chapel': 'HTC',
  'hebden bridge': 'HBD',
  heckington: 'HEC',
  'hedge end': 'HDE',
  hednesford: 'HNF',
  heighington: 'HEI',
  'helensburgh central': 'HLC',
  'helensburgh upper': 'HLU',
  hellifield: 'HLD',
  helmsdale: 'HMS',
  helsby: 'HSB',
  'hemel hempstead': 'HML',
  hendon: 'HEN',
  hengoed: 'HNG',
  'henley-in-arden': 'HNL',
  'henley-on-thames': 'HOT',
  hensall: 'HEL',
  hereford: 'HFD',
  'herne bay': 'HNB',
  'herne hill': 'HNH',
  hersham: 'HER',
  'hertford east': 'HFE',
  'hertford north': 'HFN',
  hessle: 'HES',
  heswall: 'HSW',
  hever: 'HEV',
  heworth: 'HEW',
  hexham: 'HEX',
  heyford: 'HYD',
  'heysham port': 'HHB',
  'high brooms': 'HIB',
  'high street': 'HST',
  'high wycombe': 'HWY',
  higham: 'HGM',
  'highams park': 'HIP',
  'highbridge & burnham': 'HIG',
  'highbury & islington': 'HHY',
  hightown: 'HTO',
  hildenborough: 'HLB',
  hillfoot: 'HLF',
  'hillington east': 'HLE',
  'hillington west': 'HLW',
  hillside: 'HIL',
  hilsea: 'HLS',
  'hinchley wood': 'HYW',
  hinckley: 'HNK',
  hindley: 'HIN',
  'hinton admiral': 'HNA',
  hitchin: 'HIT',
  'hither green': 'HGR',
  hockley: 'HOC',
  hollingbourne: 'HBN',
  'holmes chapel': 'HCH',
  holmwood: 'HLM',
  'holton heath': 'HOL',
  holyhead: 'HHD',
  holytown: 'HLY',
  homerton: 'HMN',
  honeybourne: 'HYB',
  honiton: 'HON',
  honley: 'HOY',
  'honor oak park': 'HPA',
  hook: 'HOK',
  hooton: 'HOO',
  'hope (flintshire)': 'HPE',
  'hope (derbyshire)': 'HOP',
  'hopton heath': 'HPT',
  horden: 'HRE',
  horley: 'HOR',
  'hornbeam park': 'HBP',
  hornsey: 'HRN',
  horsforth: 'HRS',
  horsham: 'HRH',
  horsley: 'HSY',
  'horton in ribblesdale': 'HIR',
  'horwich parkway': 'HWI',
  hoscar: 'HSC',
  'hough green': 'HGN',
  hounslow: 'HOU',
  hove: 'HOV',
  'hoveton & wroxham': 'HXM',
  'how wood': 'HWW',
  howden: 'HOW',
  howwood: 'HOZ',
  hoxton: 'HOX',
  hoylake: 'HYK',
  'hubberts bridge': 'HBB',
  hucknall: 'HKN',
  huddersfield: 'HUD',
  hull: 'HUL',
  'humphrey park': 'HUP',
  huncoat: 'HCT',
  hungerford: 'HGD',
  hunmanby: 'HUB',
  huntingdon: 'HUN',
  huntly: 'HNT',
  'hunts cross': 'HNX',
  'hurst green': 'HUR',
  'hutton cranswick': 'HUT',
  huyton: 'HUY',
  'hyde central': 'HYC',
  'hyde north': 'HYT',
  hykeham: 'HKM',
  hyndland: 'HYN',
  hythe: 'HYH',
  ifield: 'IFI',
  ilford: 'IFD',
  ilkeston: 'ILN',
  ilkley: 'ILK',
  'imperial wharf': 'IMW',
  ince: 'INC',
  'ince & elton': 'INE',
  ingatestone: 'INT',
  insch: 'INS',
  invergordon: 'IGD',
  invergowrie: 'ING',
  inverkeithing: 'INK',
  inverkip: 'INP',
  inverness: 'INV',
  'inverness airport': 'IVA',
  invershin: 'INH',
  inverurie: 'INR',
  ipswich: 'IPS',
  irlam: 'IRL',
  irvine: 'IRV',
  isleworth: 'ISL',
  islip: 'ISP',
  iver: 'IVR',
  ivybridge: 'IVY',
  'james cook university hospital': 'JCH',
  'james street': 'LVJ',
  'jewellery quarter': 'JEQ',
  johnston: 'JOH',
  johnstone: 'JHN',
  jordanhill: 'JOR',
  kearsley: 'KSL',
  kearsney: 'KSN',
  keighley: 'KEI',
  keith: 'KEH',
  kelvedon: 'KEL',
  kelvindale: 'KVD',
  kemble: 'KEM',
  'kempston hardwick': 'KMH',
  'kempton park': 'KMP',
  kemsing: 'KMS',
  kemsley: 'KML',
  kendal: 'KEN',
  kenilworth: 'KNW',
  kenley: 'KLY',
  kennett: 'KNE',
  kennishead: 'KNS',
  'kensal green': 'KNL',
  'kensal rise': 'KNR',
  'kensington olympia': 'KPA',
  'kent house': 'KTH',
  'kentish town': 'KTN',
  'kentish town west': 'KTW',
  kenton: 'KNT',
  'kents bank': 'KBK',
  kettering: 'KET',
  'kew bridge': 'KWB',
  'kew gardens': 'KWG',
  keyham: 'KEY',
  keynsham: 'KYN',
  kidbrooke: 'KDB',
  kidderminster: 'KID',
  kidsgrove: 'KDG',
  kidwelly: 'KWL',
  'kilburn high road': 'KBN',
  kildale: 'KLD',
  kildonan: 'KIL',
  kilgetty: 'KGT',
  kilmarnock: 'KMK',
  kilmaurs: 'KLM',
  kilpatrick: 'KPT',
  kilwinning: 'KWN',
  kinbrace: 'KBC',
  kingham: 'KGM',
  kinghorn: 'KGH',
  'kings langley': 'KGL',
  'kings lynn': 'KLN',
  'kings norton': 'KNN',
  'kings nympton': 'KGN',
  'kings park': 'KGP',
  'kings sutton': 'KGS',
  kingsknowe: 'KGE',
  kingston: 'KNG',
  kingswood: 'KND',
  kingussie: 'KIN',
  kintbury: 'KIT',
  kintore: 'KTR',
  'kirby cross': 'KBX',
  'kirk sandall': 'KKS',
  kirkby: 'KIR',
  'kirkby in ashfield': 'KKB',
  'kirkby stephen': 'KSW',
  'kirkby-in-furness': 'KBF',
  kirkcaldy: 'KDY',
  kirkconnel: 'KRK',
  kirkdale: 'KKD',
  'kirkham & wesham': 'KKM',
  kirkhill: 'KKH',
  kirknewton: 'KKN',
  'kirkstall forge': 'KLF',
  kirkwood: 'KWD',
  'kirton lindsey': 'KTL',
  'kiveton bridge': 'KIV',
  'kiveton park': 'KVP',
  knaresborough: 'KNA',
  knebworth: 'KBW',
  knighton: 'KNI',
  knockholt: 'KCK',
  knottingley: 'KNO',
  knucklas: 'KNU',
  knutsford: 'KNF',
  'kyle of lochalsh': 'KYL',
  ladybank: 'LDY',
  ladywell: 'LAD',
  laindon: 'LAI',
  lairg: 'LRG',
  lake: 'LKE',
  lakenheath: 'LAK',
  lamphey: 'LAM',
  lanark: 'LNK',
  lancaster: 'LAN',
  lancing: 'LAC',
  landywood: 'LAW',
  langbank: 'LGB',
  langho: 'LHO',
  langholm: 'LHL',
  langley: 'LNY',
  'langley green': 'LGG',
  'langley mill': 'LGM',
  langside: 'LGS',
  langwathby: 'LGW',
  'langwith - whaley thorns': 'LAG',
  lapford: 'LAP',
  lapworth: 'LPW',
  larbert: 'LBT',
  largs: 'LAR',
  larkhall: 'LRH',
  laurencekirk: 'LAU',
  'lawrence hill': 'LWH',
  layton: 'LAY',
  'lazonby & kirkoswald': 'LZB',
  'lea bridge': 'LEB',
  'lea green': 'LEG',
  'lea hall': 'LEH',
  leagrave: 'LEA',
  lealholm: 'LHM',
  'leamington spa': 'LMS',
  leasowe: 'LSW',
  leatherhead: 'LHD',
  ledbury: 'LED',
  lee: 'LEE',
  leeds: 'LDS',
  leicester: 'LEI',
  'leigh (kent)': 'LIH',
  'leigh-on-sea': 'LES',
  'leighton buzzard': 'LBZ',
  'lelant saltings': 'LTS',
  lelant: 'LEL',
  lenham: 'LEN',
  lenzie: 'LNZ',
  leominster: 'LEO',
  'letchworth garden city': 'LET',
  leuchars: 'LEU',
  leven: 'LEV',
  levenshulme: 'LVM',
  lewes: 'LWS',
  lewisham: 'LEW',
  leyland: 'LEY',
  'leyton midland road': 'LEM',
  'leytonstone high road': 'LER',
  'lichfield city': 'LIC',
  'lichfield trent valley': 'LTV',
  lidlington: 'LID',
  limehouse: 'LHS',
  'lincoln central': 'LCN',
  lingfield: 'LFD',
  lingwood: 'LGD',
  linlithgow: 'LIN',
  liphook: 'LIP',
  liskeard: 'LSK',
  liss: 'LIS',
  'lisvane & thornhill': 'LVT',
  'little kimble': 'LTK',
  'little sutton': 'LTT',
  littleborough: 'LTL',
  littlehampton: 'LIT',
  littlehaven: 'LVN',
  littleport: 'LTP',
  'liverpool central': 'LVC',
  'liverpool lime street': 'LIV',
  'liverpool south parkway': 'LPY',
  'livingston north': 'LSN',
  'livingston south': 'LVG',
  llanaber: 'LLA',
  llanbedr: 'LBR',
  'llanbister road': 'LLT',
  llanbradach: 'LNB',
  llandaf: 'LLN',
  llandanwg: 'LDN',
  llandecwyn: 'LLC',
  llandeilo: 'LLL',
  llandovery: 'LLV',
  llandrindod: 'LLO',
  llandudno: 'LLD',
  'llandudno junction': 'LLJ',
  llandybie: 'LLI',
  llanelli: 'LLE',
  llanfairfechan: 'LLF',
  llanfairpwll: 'LPG',
  llangadog: 'LLG',
  llangammarch: 'LLM',
  llangennech: 'LLH',
  llangynllo: 'LGO',
  llanharan: 'LLR',
  llanhilleth: 'LTH',
  llanishen: 'LLS',
  llanrwst: 'LWR',
  llansamlet: 'LAS',
  'llantwit major': 'LWM',
  llanwrda: 'LNR',
  llanwrtyd: 'LNW',
  llwyngwril: 'LLW',
  llwynypia: 'LLY',
  'loch awe': 'LHA',
  'loch eil outward bound': 'LHE',
  lochailort: 'LCL',
  locheilside: 'LCS',
  lochgelly: 'LCG',
  lochluichart: 'LCC',
  lochwinnoch: 'LHW',
  lockerbie: 'LOC',
  lockwood: 'LCK',
  'london blackfriars': 'BFR',
  'london bridge': 'LBG',
  'london cannon street': 'CST',
  'london charing cross': 'CHX',
  'london euston': 'EUS',
  'london fenchurch street': 'FST',
  'london fields': 'LOF',
  'london kings cross': 'KGX',
  'london liverpool street': 'LST',
  'london marylebone': 'MYB',
  'london paddington': 'PAD',
  'london road (brighton)': 'LRB',
  'london road (guildford)': 'LRD',
  'london st pancras international': 'STP',
  'london victoria': 'VIC',
  'london waterloo': 'WAT',
  'london waterloo east': 'WAE',
  'long buckby': 'LBK',
  'long eaton': 'LGE',
  'long preston': 'LPR',
  longbeck: 'LGK',
  longbridge: 'LOB',
  longcross: 'LNG',
  longfield: 'LGF',
  longniddry: 'LND',
  longport: 'LPT',
  longton: 'LGN',
  looe: 'LOO',
  lostock: 'LOT',
  'lostock gralam': 'LTG',
  'lostock hall': 'LOH',
  lostwithiel: 'LOS',
  loughborough: 'LBO',
  'loughborough junction': 'LGJ',
  'low moor': 'LMR',
  lowdham: 'LOW',
  'lower sydenham': 'LSY',
  lowestoft: 'LWT',
  ludlow: 'LUD',
  luton: 'LUT',
  'luton airport parkway': 'LTN',
  luxulyan: 'LUX',
  lydney: 'LYD',
  lye: 'LYE',
  'lymington pier': 'LYP',
  'lymington town': 'LYT',
  'lympstone commando': 'LYC',
  'lympstone village': 'LYM',
  lytham: 'LTM',
  macclesfield: 'MAC',
  machynlleth: 'MCN',
  'maesteg (ewenny road)': 'MEW',
  maesteg: 'MST',
  maghull: 'MAG',
  'maghull north': 'MNS',
  'maiden newton': 'MDN',
  maidenhead: 'MAI',
  'maidstone barracks': 'MDB',
  'maidstone east': 'MDE',
  'maidstone west': 'MDW',
  'malden manor': 'MAL',
  mallaig: 'MLG',
  malton: 'MLT',
  'malvern link': 'MVL',
  'manchester airport': 'MIA',
  'manchester oxford road': 'MCO',
  'manchester piccadilly': 'MAN',
  'manchester united football club': 'MUF',
  'manchester victoria': 'MCV',
  manea: 'MNE',
  manningtree: 'MNG',
  'manor park': 'MNP',
  'manor road': 'MNR',
  manorbier: 'MRB',
  manors: 'MAS',
  mansfield: 'MFT',
  'mansfield woodhouse': 'MSW',
  march: 'MCH',
  marden: 'MRN',
  margate: 'MAR',
  'market harborough': 'MHR',
  'market rasen': 'MKR',
  markinch: 'MNC',
  'marks tey': 'MKT',
  marlow: 'MLW',
  marple: 'MPL',
  marsden: 'MSN',
  'marsh barton': 'MBT',
  marske: 'MSK',
  'marston green': 'MGN',
  'martin mill': 'MTM',
  'martins heron': 'MAO',
  marton: 'MTO',
  maryhill: 'MYH',
  maryland: 'MYL',
  maryport: 'MRY',
  'matlock bath': 'MTB',
  matlock: 'MAT',
  'mauldeth road': 'MAU',
  'maxwell park': 'MAX',
  maybole: 'MAY',
  'maze hill': 'MZH',
  meadowhall: 'MHS',
  meldreth: 'MEL',
  melksham: 'MKM',
  melrose: 'MLS',
  melton: 'MES',
  'melton mowbray': 'MMO',
  menheniot: 'MEN',
  menston: 'MNN',
  meols: 'MEO',
  'meols cop': 'MEC',
  meopham: 'MEP',
  'meridian water': 'MRW',
  merryton: 'MEY',
  merstham: 'MHM',
  'merthyr tydfil': 'MER',
  'merthyr vale': 'MEV',
  metheringham: 'MGM',
  metrocentre: 'MCE',
  mexborough: 'MEX',
  micheldever: 'MIC',
  micklefield: 'MIK',
  middlesbrough: 'MBR',
  middlewood: 'MDL',
  midgham: 'MDG',
  'milford (surrey)': 'MLF',
  'milford haven': 'MFH',
  'mill hill (lancs)': 'MLH',
  'mill hill broadway': 'MIL',
  'millbrook (bedfordshire)': 'MLB',
  'millbrook (hants)': 'MBK',
  'milliken park': 'MIN',
  millom: 'MLM',
  'mills hill': 'MIH',
  milngavie: 'MLN',
  'milton keynes central': 'MKC',
  minffordd: 'MFF',
  minster: 'MSR',
  mirfield: 'MIR',
  mistley: 'MIS',
  'mitcham eastfields': 'MTC',
  'mitcham junction': 'MIJ',
  mobberley: 'MOB',
  monifieth: 'MON',
  'monks risborough': 'MRS',
  montpelier: 'MTP',
  montrose: 'MTS',
  moorfields: 'MRF',
  moorgate: 'MOG',
  moorside: 'MSD',
  moorthorpe: 'MRP',
  morar: 'MRR',
  'morchard road': 'MRD',
  'morden south': 'MDS',
  morecambe: 'MCM',
  'moreton (dorset)': 'MTN',
  'moreton (merseyside)': 'MRT',
  'moreton-in-marsh': 'MIM',
  'morfa mawddach': 'MFA',
  morley: 'MLY',
  morpeth: 'MPT',
  mortimer: 'MOR',
  mortlake: 'MTL',
  'moses gate': 'MSS',
  'moss side': 'MOS',
  'mossley (manchester)': 'MSL',
  'mossley hill': 'MSH',
  mosspark: 'MPK',
  moston: 'MSO',
  motherwell: 'MTH',
  'motspur park': 'MOT',
  mottingham: 'MTG',
  'mottisfont & dunbridge': 'DBG',
  mouldsworth: 'MLD',
  moulsecoomb: 'MCB',
  'mount florida': 'MFL',
  'mount vernon': 'MTV',
  'mountain ash': 'MTA',
  'muir of ord': 'MOO',
  muirend: 'MUI',
  musselburgh: 'MUB',
  mytholmroyd: 'MYT',
  nafferton: 'NFN',
  'nailsea & backwell': 'NLS',
  nairn: 'NRN',
  nantwich: 'NAN',
  narberth: 'NAR',
  narborough: 'NBR',
  'navigation road': 'NVR',
  neath: 'NTH',
  'needham market': 'NMT',
  neilston: 'NEI',
  nelson: 'NEL',
  neston: 'NES',
  netherfield: 'NET',
  nethertown: 'NRT',
  netley: 'NTL',
  'new barnet': 'NBA',
  'new beckenham': 'NBC',
  'new brighton': 'NBN',
  'new clee': 'NCE',
  'new cross gate': 'NXG',
  'new cross': 'NWX',
  'new cumnock': 'NCK',
  'new eltham': 'NEH',
  'new holland': 'NHL',
  'new hythe': 'NHE',
  'new lane': 'NLN',
  'new malden': 'NEM',
  'new mills central': 'NMC',
  'new mills newtown': 'NMN',
  'new milton': 'NWM',
  'new pudsey': 'NPD',
  'new southgate': 'NSG',
  'newark castle': 'NCT',
  'newark northgate': 'NNG',
  newbridge: 'NBE',
  'newbury park': 'ZNP',
  'newbury racecourse': 'NRC',
  newbury: 'NBY',
  newcastle: 'NCL',
  'newcastle airport': 'APN',
  newcourt: 'NCO',
  newcraighall: 'NEW',
  'newhaven harbour': 'NVH',
  'newhaven town': 'NVN',
  newington: 'NGT',
  newmarket: 'NMK',
  'newport (essex)': 'NWE',
  'newport (south wales)': 'NWP',
  newquay: 'NQY',
  newstead: 'NSD',
  newton: 'NTN',
  'newton abbot': 'NTA',
  'newton aycliffe': 'NAY',
  'newton for hyde': 'NWN',
  'newton heath and moston': 'NMM',
  'newton st cyres': 'NTC',
  newtongrange: 'NEG',
  'newton-le-willows': 'NLW',
  newtonmore: 'NWR',
  'newton-on-ayr': 'NOA',
  'newtown (powys)': 'NWT',
  'ninian park': 'NNP',
  nitshill: 'NIT',
  norbiton: 'NBT',
  norbury: 'NRB',
  'normans bay': 'NSB',
  normanton: 'NOR',
  'north berwick': 'NBW',
  'north camp': 'NCM',
  'north dulwich': 'NDL',
  'north fambridge': 'NFA',
  'north llanrwst': 'NLR',
  'north queensferry': 'NQU',
  'north road': 'NRD',
  'north sheen': 'NSH',
  'north walsham': 'NWA',
  'north wembley': 'NWB',
  northallerton: 'NTR',
  northampton: 'NMP',
  northfield: 'NFD',
  'northfleet - cooper arms': 'NFL',
  'northolt park': 'NLT',
  'northumberland park': 'NUM',
  northwich: 'NWI',
  'norton bridge': 'NTB',
  norwich: 'NRW',
  'norwood junction': 'NWD',
  nottingham: 'NOT',
  nuneaton: 'NUN',
  nunhead: 'NHD',
  nunthorpe: 'NNT',
  nutbourne: 'NUT',
  nutfield: 'NUF',
  oakengates: 'OKN',
  oakham: 'OKM',
  'oakleigh park': 'OKL',
  oban: 'OBN',
  ockendon: 'OCK',
  ockley: 'OLY',
  okehampton: 'OKE',
  'old hill': 'OHL',
  'old roan': 'ORN',
  'old street': 'OLD',
  'oldfield park': 'OLF',
  olton: 'OLT',
  ore: 'ORE',
  ormskirk: 'OMS',
  orpington: 'ORP',
  orrell: 'ORR',
  'orrell park': 'OPK',
  otford: 'OTF',
  'oulton broad north': 'OUN',
  'oulton broad south': 'OUS',
  outwood: 'OUT',
  overpool: 'OVE',
  overton: 'OVR',
  'oxenholme lake district': 'OXN',
  oxford: 'OXF',
  'oxford parkway': 'OXP',
  oxshott: 'OXS',
  oxted: 'OXT',
  'paddock wood': 'PDW',
  padgate: 'PDG',
  paignton: 'PGN',
  'paisley canal': 'PCN',
  'paisley gilmour street': 'PYG',
  'paisley st james': 'PYJ',
  'palmers green': 'PAL',
  pangbourne: 'PAN',
  pannal: 'PNL',
  pantyffynnon: 'PTF',
  par: 'PAR',
  parbold: 'PBL',
  'park street': 'PKT',
  'parkstone (dorset)': 'PKS',
  'parson street': 'PSN',
  partick: 'PTK',
  parton: 'PRN',
  patchway: 'PWY',
  patricroft: 'PAT',
  patterton: 'PTT',
  peartree: 'PEA',
  'peckham rye': 'PMR',
  pegswood: 'PEG',
  pemberton: 'PEM',
  'pembrey & burry port': 'PBY',
  'pembroke dock': 'PMD',
  pembroke: 'PMB',
  penally: 'PNA',
  penarth: 'PEN',
  pencoed: 'PCD',
  pengam: 'PGM',
  'penge east': 'PNE',
  'penge west': 'PNW',
  penhelig: 'PHG',
  penistone: 'PNS',
  penkridge: 'PKG',
  penmaenmawr: 'PMW',
  penmere: 'PNM',
  penrhiwceiber: 'PER',
  penrhyndeudraeth: 'PRH',
  penrith: 'PNR',
  penryn: 'PYN',
  pensarn: 'PES',
  penshurst: 'PHR',
  'pentre-bach': 'PTB',
  'pen-y-bont': 'PNY',
  penychain: 'PNC',
  penyffordd: 'PNF',
  penzance: 'PNZ',
  perranwell: 'PRW',
  'perry barr': 'PRY',
  pershore: 'PSH',
  perth: 'PTH',
  peterborough: 'PBO',
  petersfield: 'PTR',
  'petts wood': 'PET',
  'pevensey & westham': 'PEV',
  'pevensey bay': 'PEB',
  pewsey: 'PEW',
  'pickering eastgate': 'PIZ',
  pilning: 'PIL',
  pinhoe: 'PIN',
  pitlochry: 'PIT',
  pitsea: 'PSE',
  pleasington: 'PLS',
  plockton: 'PLK',
  pluckley: 'PLC',
  plumley: 'PLM',
  plumpton: 'PMP',
  plumstead: 'PLU',
  plymouth: 'PLY',
  pokesdown: 'POK',
  polegate: 'PLG',
  polesworth: 'PSW',
  'pollokshaws east': 'PWE',
  'pollokshaws west': 'PWW',
  'pollokshields east': 'PLE',
  'pollokshields west': 'PLW',
  polmont: 'PMT',
  'polsloe bridge': 'POL',
  'ponders end': 'PON',
  pontarddulais: 'PTD',
  'pontefract baghill': 'PFR',
  'pontefract monkhill': 'PFM',
  'pontefract tanshelf': 'POT',
  pontlottyn: 'PLT',
  pontyclun: 'PYC',
  'pont-y-pant': 'PYP',
  'pontypool and new inn': 'PPL',
  pontypridd: 'PPD',
  poole: 'POO',
  poppleton: 'POP',
  'port glasgow': 'PTG',
  'port sunlight': 'PSL',
  'port talbot parkway': 'PTA',
  portchester: 'PTC',
  porth: 'POR',
  porthmadog: 'PTM',
  portlethen: 'PLN',
  portslade: 'PLD',
  'portsmouth & southsea': 'PMS',
  'portsmouth arms': 'PMA',
  'portsmouth harbour': 'PMH',
  'portway park & ride': 'PRI',
  'possilpark & parkhouse': 'PPK',
  'potters bar': 'PBR',
  'poulton-le-fylde': 'PFY',
  poynton: 'PYT',
  prees: 'PRS',
  prescot: 'PSC',
  prestatyn: 'PRT',
  prestbury: 'PRB',
  preston: 'PRE',
  'preston park': 'PRP',
  prestonpans: 'PST',
  'prestwick international airport': 'PRA',
  'prestwick town': 'PTW',
  'priesthill & darnley': 'PTL',
  'princes risborough': 'PRR',
  prittlewell: 'PRL',
  prudhoe: 'PRU',
  pulborough: 'PUL',
  purfleet: 'PFL',
  'purley oaks': 'PUO',
  purley: 'PUR',
  putney: 'PUT',
  pwllheli: 'PWL',
  'pye corner': 'PYE',
  pyle: 'PYL',
  'quakers yard': 'QYD',
  queenborough: 'QBR',
  'queens park (glasgow)': 'QPK',
  'queens park (london)': 'QPW',
  'queens road peckham': 'QRP',
  'queenstown road (battersea)': 'QRB',
  'quintrell downs': 'QUI',
  'radcliffe (nottinghamshire)': 'RDF',
  radlett: 'RDT',
  radley: 'RAD',
  radyr: 'RDR',
  rainford: 'RNF',
  'rainham (essex)': 'RNM',
  'rainham (kent)': 'RAI',
  rainhill: 'RNH',
  ramsgate: 'RAM',
  'ramsgreave & wilpshire': 'RGW',
  rannoch: 'RAN',
  rauceby: 'RAU',
  'ravenglass for eskdale': 'RAV',
  ravensbourne: 'RVB',
  ravensthorpe: 'RVN',
  rawcliffe: 'RWC',
  rayleigh: 'RLG',
  'raynes park': 'RAY',
  reading: 'RDG',
  'reading green park': 'RGP',
  'reading west': 'RDW',
  'rectory road': 'REC',
  redbridge: 'RDB',
  'redcar central': 'RCC',
  'redcar east': 'RCE',
  'reddish north': 'RDN',
  'reddish south': 'RDS',
  redditch: 'RDC',
  redhill: 'RDH',
  redland: 'RDA',
  redruth: 'RED',
  'reedham (london)': 'RHM',
  'reedham (norfolk)': 'REE',
  reigate: 'REI',
  renton: 'RTN',
  reston: 'RSN',
  retford: 'RET',
  rhiwbina: 'RHI',
  'rhoose cardiff airport': 'RIA',
  rhosneigr: 'RHO',
  rhyl: 'RHL',
  rhymney: 'RHY',
  ribblehead: 'RHD',
  'rice lane': 'RIL',
  richmond: 'RMD',
  rickmansworth: 'RIC',
  riddlesdown: 'RDD',
  ridgmont: 'RID',
  'riding mill': 'RDM',
  'risca & pontymister': 'RCA',
  rishton: 'RIS',
  robertsbridge: 'RBR',
  robroyston: 'RRN',
  roby: 'ROB',
  rochdale: 'RCD',
  roche: 'ROC',
  rochester: 'RTR',
  rochford: 'RFD',
  'rock ferry': 'RFY',
  rogart: 'ROG',
  rogerstone: 'ROR',
  rolleston: 'ROL',
  'roman bridge': 'RMB',
  romford: 'RMF',
  romiley: 'RML',
  romsey: 'ROM',
  roose: 'ROO',
  'rose grove': 'RSG',
  'rose hill marple': 'RSH',
  rosyth: 'ROS',
  'rotherham central': 'RMC',
  rotherhithe: 'ROE',
  'roughton road': 'RNR',
  'rowlands castle': 'RLN',
  'rowley regis': 'ROW',
  'roy bridge': 'RYB',
  roydon: 'RYN',
  royston: 'RYS',
  ruabon: 'RUA',
  rufford: 'RUF',
  rugby: 'RUG',
  'rugeley town': 'RGT',
  'rugeley trent valley': 'RGL',
  runcorn: 'RUN',
  'runcorn east': 'RUE',
  ruskington: 'RKT',
  ruswarp: 'RUS',
  rutherglen: 'RUT',
  'ryde esplanade': 'RYD',
  'ryde pier head': 'RYP',
  'ryde st johns road': 'RYR',
  'ryder brow': 'RRB',
  rye: 'RYE',
  'rye house': 'RYH',
  'salford central': 'SFD',
  'salford crescent': 'SLD',
  salfords: 'SAF',
  salhouse: 'SAH',
  salisbury: 'SAL',
  saltaire: 'SAE',
  saltash: 'STS',
  saltburn: 'SLB',
  saltcoats: 'SLT',
  saltmarshe: 'SAM',
  salwick: 'SLW',
  'sandal & agbrigg': 'SNA',
  sandbach: 'SDB',
  sanderstead: 'SNR',
  sandhills: 'SDL',
  sandhurst: 'SND',
  sandling: 'SDG',
  sandown: 'SAN',
  sandplace: 'SDP',
  'sandwell & dudley': 'SAD',
  sandwich: 'SDW',
  sandy: 'SDY',
  'sankey for penketh': 'SNK',
  sanquhar: 'SQH',
  sarn: 'SRR',
  saundersfoot: 'SDF',
  saunderton: 'SDR',
  sawbridgeworth: 'SAW',
  saxilby: 'SXY',
  saxmundham: 'SAX',
  scarborough: 'SCA',
  scotscalder: 'SCT',
  scotstounhill: 'SCH',
  scunthorpe: 'SCU',
  'sea mills': 'SML',
  seaburn: 'SEB',
  seaford: 'SEF',
  'seaforth & litherland': 'SFL',
  seaham: 'SEA',
  seamer: 'SEM',
  seascale: 'SSC',
  'seaton carew': 'SEC',
  'seaton delaval': 'SEJ',
  'seer green & jordans': 'SRG',
  selby: 'SBY',
  selhurst: 'SRS',
  selkirk: 'SKK',
  sellafield: 'SEL',
  selling: 'SEG',
  'selly oak': 'SLY',
  settle: 'SET',
  'seven kings': 'SVK',
  'seven sisters': 'SVS',
  sevenoaks: 'SEV',
  'severn beach': 'SVB',
  'severn tunnel junction': 'STJ',
  shadwell: 'SDE',
  shalford: 'SFR',
  shanklin: 'SHN',
  shawfair: 'SFI',
  shawford: 'SHW',
  shawlands: 'SHL',
  'sheerness-on-sea': 'SSS',
  sheffield: 'SHF',
  shelford: 'SED',
  shenfield: 'SNF',
  shenstone: 'SEN',
  'shepherds bush': 'SPB',
  'shepherds well': 'SPH',
  shepley: 'SPY',
  shepperton: 'SHP',
  shepreth: 'STH',
  sherborne: 'SHE',
  'sherburn-in-elmet': 'SIE',
  sheringham: 'SHM',
  shettleston: 'SLS',
  shieldmuir: 'SDM',
  shifnal: 'SFN',
  shildon: 'SHD',
  shiplake: 'SHI',
  shipley: 'SHY',
  'shippea hill': 'SPP',
  shipton: 'SIP',
  shirebrook: 'SHB',
  shirehampton: 'SHH',
  shireoaks: 'SRO',
  shirley: 'SRL',
  shoeburyness: 'SRY',
  sholing: 'SHO',
  'shoreditch high street': 'SDC',
  'shoreham (kent)': 'SEH',
  'shoreham-by-sea': 'SSE',
  shortlands: 'SRT',
  shotton: 'SHT',
  shotts: 'SHS',
  shrewsbury: 'SHR',
  sidcup: 'SID',
  sileby: 'SIL',
  silecroft: 'SIC',
  'silkstone common': 'SLK',
  'silver street': 'SLV',
  silverdale: 'SVR',
  singer: 'SIN',
  sittingbourne: 'SIT',
  skegness: 'SKG',
  skewen: 'SKE',
  skipton: 'SKI',
  'slade green': 'SGR',
  slaithwaite: 'SWT',
  slateford: 'SLA',
  sleaford: 'SLR',
  sleights: 'SLH',
  slough: 'SLO',
  'small heath': 'SMA',
  'smallbrook junction': 'SAB',
  'smethwick galton bridge': 'SGB',
  'smethwick rolfe street': 'SMR',
  'smithy bridge': 'SMB',
  snaith: 'SNI',
  snodland: 'SDA',
  snowdown: 'SWO',
  'sole street': 'SOR',
  solihull: 'SOL',
  soham: 'SOJ',
  somerleyton: 'SYT',
  'south acton': 'SAT',
  'south bank': 'SBK',
  'south bermondsey': 'SBM',
  'south croydon': 'SCY',
  'south elmsall': 'SES',
  'south greenford': 'SGN',
  'south gyle': 'SGL',
  'south hampstead': 'SOH',
  'south kenton': 'SOK',
  'south merton': 'SMO',
  'south milford': 'SOM',
  'south ruislip': 'SRU',
  'south tottenham': 'STO',
  'south wigston': 'SWS',
  'south woodham ferrers': 'SOF',
  southall: 'STL',
  'southampton airport parkway': 'SOA',
  'southampton central': 'SOU',
  'southampton town quay': 'STQ',
  southbourne: 'SOB',
  southbury: 'SBU',
  southease: 'SEE',
  'southend airport': 'SIA',
  'southend central': 'SOC',
  'southend east': 'SOE',
  'southend victoria': 'SOV',
  southminster: 'SMN',
  southport: 'SOP',
  southwick: 'SWK',
  'sowerby bridge': 'SOW',
  spalding: 'SPA',
  'spean bridge': 'SBR',
  spital: 'SPI',
  spondon: 'SPO',
  'spooner row': 'SPN',
  'spring road': 'SRI',
  springburn: 'SPR',
  springfield: 'SPF',
  'squires gate': 'SQU',
  'st albans': 'SAC',
  'st albans abbey': 'SAA',
  'st andrews road': 'SAR',
  'st annes-on-the-sea': 'SAS',
  'st austell': 'SAU',
  'st bees': 'SBS',
  'st budeaux ferry road': 'SBF',
  'st budeaux victoria road': 'SBV',
  'st columb road': 'SCR',
  'st denys': 'SDN',
  'st erth': 'SER',
  'st germans': 'SGM',
  'st helens central': 'SNH',
  'st helens junction': 'SHJ',
  'st helier': 'SIH',
  'st ives': 'SIV',
  "st james' park": 'SJP',
  'st james street': 'SJS',
  'st johns': 'SAJ',
  'st keyne': 'SKN',
  'st leonards warrior square': 'SLQ',
  'st margarets (london)': 'SMG',
  'st margarets (herts)': 'SMT',
  'st mary cray': 'SMY',
  'st michaels': 'STM',
  'st neots': 'SNO',
  'st peters': 'STZ',
  'stadium of light': 'STI',
  stafford: 'STA',
  staines: 'SNS',
  stallingborough: 'SLL',
  stalybridge: 'SYB',
  stamford: 'SMD',
  'stamford hill': 'SMH',
  'stanford-le-hope': 'SFO',
  'stanlow & thornton': 'SNT',
  'stansted airport': 'SSD',
  'stansted mountfitchet': 'SST',
  staplehurst: 'SPU',
  'stapleton road': 'SRD',
  starbeck: 'SBE',
  starcross: 'SCS',
  staveley: 'SVL',
  stechford: 'SCF',
  'steeton & silsden': 'SON',
  stepps: 'SPS',
  stevenage: 'SVG',
  stevenston: 'STV',
  stewartby: 'SWR',
  stewarton: 'STT',
  stirling: 'STG',
  stockport: 'SPT',
  stocksfield: 'SKS',
  stocksmoor: 'SSM',
  stockton: 'STK',
  'stoke mandeville': 'SKM',
  'stoke newington': 'SKW',
  'stoke-on-trent': 'SOT',
  stone: 'SNE',
  'stone crossing': 'SCG',
  'stonebridge park': 'SBP',
  stonegate: 'SOG',
  stonehaven: 'STN',
  stonehouse: 'SHU',
  stoneleigh: 'SNL',
  'stourbridge junction': 'SBJ',
  'stourbridge town': 'SBT',
  stow: 'SOI',
  stowmarket: 'SMK',
  stranraer: 'STR',
  'stratford international': 'SFA',
  'stratford (london)': 'SRA',
  'stratford-upon-avon parkway': 'STY',
  'stratford-upon-avon': 'SAV',
  strathcarron: 'STC',
  'strawberry hill': 'STW',
  'streatham common': 'SRC',
  'streatham hill': 'SRH',
  streatham: 'STE',
  streethouse: 'SHC',
  strines: 'SRN',
  stromeferry: 'STF',
  strood: 'SOO',
  stroud: 'STD',
  sturry: 'STU',
  styal: 'SYA',
  'sudbury & harrow road': 'SUD',
  'sudbury hill harrow': 'SDH',
  'sudbury suffolk': 'SUY',
  'sugar loaf': 'SUG',
  summerston: 'SUM',
  sunbury: 'SUU',
  sunderland: 'SUN',
  'sundridge park': 'SUP',
  sunningdale: 'SNG',
  sunnymeads: 'SNY',
  surbiton: 'SUR',
  'surrey quays': 'SQE',
  'sutton (london)': 'SUO',
  'sutton coldfield': 'SUT',
  'sutton common': 'SUC',
  'sutton parkway': 'SPK',
  swale: 'SWL',
  swanley: 'SAY',
  'swanscombe- george & dragon': 'SWM',
  swansea: 'SWA',
  swanwick: 'SNW',
  sway: 'SWY',
  swaythling: 'SWG',
  swinderby: 'SWD',
  swindon: 'SWI',
  swineshead: 'SWE',
  'swinton (manchester)': 'SNN',
  'swinton (south yorks)': 'SWN',
  'sydenham hill': 'SYH',
  sydenham: 'SYD',
  'syon lane': 'SYL',
  syston: 'SYS',
  tackley: 'TAC',
  tadworth: 'TAD',
  'taffs well': 'TAF',
  tain: 'TAI',
  talsarnau: 'TAL',
  talybont: 'TLB',
  'tal-y-cafn': 'TLC',
  'tame bridge parkway': 'TAB',
  tamworth: 'TAM',
  'tan-y-bwlch': 'TYB',
  taplow: 'TAP',
  'tattenham corner': 'TAT',
  taunton: 'TAU',
  taynuilt: 'TAY',
  teddington: 'TED',
  'teesside airport': 'TEA',
  teignmouth: 'TGM',
  'telford central': 'TFC',
  templecombe: 'TMC',
  tenby: 'TEN',
  teynham: 'TEY',
  'thames ditton': 'THD',
  'thanet parkway': 'THP',
  thatcham: 'THA',
  'thatto heath': 'THH',
  'the hawthorns': 'THW',
  'the lakes': 'TLK',
  theale: 'THE',
  'theobalds grove': 'TEO',
  thetford: 'TTF',
  thirsk: 'THI',
  thornaby: 'TBY',
  'thorne north': 'TNN',
  'thorne south': 'TNS',
  thornford: 'THO',
  thornliebank: 'THB',
  'thornton abbey': 'TNA',
  'thornton heath': 'TTH',
  thorntonhall: 'THT',
  'thorpe bay': 'TPB',
  'thorpe culvert': 'TPC',
  'thorpe-le-soken': 'TLS',
  'three bridges': 'TBD',
  'three oaks': 'TOK',
  thurgarton: 'THU',
  thurnscoe: 'THC',
  thurso: 'THS',
  thurston: 'TRS',
  'tilbury riverside': 'TBR',
  'tilbury town': 'TIL',
  'tile hill': 'THL',
  tilehurst: 'TLH',
  tipton: 'TIP',
  'tir-phil': 'TIR',
  tisbury: 'TIS',
  'tiverton parkway': 'TVP',
  todmorden: 'TOD',
  tolworth: 'TOL',
  'ton pentre': 'TPN',
  tonbridge: 'TON',
  tondu: 'TDU',
  tonfanau: 'TNF',
  tonypandy: 'TNP',
  tooting: 'TOO',
  topsham: 'TOP',
  torquay: 'TQY',
  torre: 'TRR',
  totnes: 'TOT',
  'tottenham court road': 'TCR',
  'tottenham hale': 'TOM',
  totton: 'TTN',
  'town green': 'TWN',
  'trafford park': 'TRA',
  'trefforest estate': 'TRE',
  trefforest: 'TRF',
  trehafod: 'TRH',
  treherbert: 'TRB',
  treorchy: 'TRY',
  trimley: 'TRM',
  tring: 'TRI',
  'troed-y-rhiw': 'TRD',
  troon: 'TRN',
  trowbridge: 'TRO',
  truro: 'TRU',
  tulloch: 'TUL',
  'tulse hill': 'TUH',
  'tunbridge wells': 'TBW',
  'turkey street': 'TUR',
  'tutbury & hatton': 'TUT',
  tweedbank: 'TWB',
  twickenham: 'TWI',
  twyford: 'TWY',
  'ty croes': 'TYC',
  'ty glas': 'TGS',
  tygwyn: 'TYG',
  'tyndrum lower': 'TYL',
  tyseley: 'TYS',
  tywyn: 'TYW',
  uckfield: 'UCK',
  uddingston: 'UDD',
  ulceby: 'ULC',
  ulleskelf: 'ULL',
  ulverston: 'ULV',
  umberleigh: 'UMB',
  'university (birmingham)': 'UNI',
  uphall: 'UHA',
  upholland: 'UPL',
  upminster: 'UPM',
  'upper halliford': 'UPH',
  'upper holloway': 'UHL',
  'upper tyndrum': 'UTY',
  'upper warlingham': 'UWL',
  upton: 'UPT',
  upwey: 'UPW',
  urmston: 'URM',
  uttoxeter: 'UTT',
  valley: 'VAL',
  vauxhall: 'VXH',
  'virginia water': 'VIR',
  waddon: 'WDO',
  wadhurst: 'WAD',
  wainfleet: 'WFL',
  'wakefield kirkgate': 'WKK',
  'wakefield westgate': 'WKF',
  walkden: 'WKD',
  'wallasey grove road': 'WLG',
  'wallasey village': 'WLV',
  wallington: 'WLT',
  wallyford: 'WAF',
  walmer: 'WAM',
  walsall: 'WSL',
  walsden: 'WDN',
  'waltham cross': 'WLC',
  'walthamstow central': 'WHC',
  'walthamstow queens road': 'WMW',
  'walton (merseyside)': 'WAO',
  'walton-on-thames': 'WAL',
  'walton-on-the-naze': 'WON',
  wanborough: 'WAN',
  'wandsworth common': 'WSW',
  'wandsworth road': 'WWR',
  'wandsworth town': 'WNT',
  'wanstead park': 'WNP',
  wapping: 'WPE',
  warblington: 'WBL',
  ware: 'WAR',
  wareham: 'WRM',
  wargrave: 'WGV',
  warminster: 'WMN',
  warnham: 'WNH',
  'warrington bank quay': 'WBQ',
  'warrington central': 'WAC',
  'warrington west': 'WAW',
  warwick: 'WRW',
  'warwick parkway': 'WRP',
  'water orton': 'WTO',
  waterbeach: 'WBC',
  wateringbury: 'WTR',
  'waterloo (merseyside)': 'WLO',
  'watford high street': 'WFH',
  'watford junction': 'WFJ',
  'watford north': 'WFN',
  watlington: 'WTG',
  'watton-at-stone': 'WAS',
  'waun-gron park': 'WNG',
  'wavertree technology park': 'WAV',
  wedgwood: 'WED',
  'wedgwood lane': 'WER',
  weeley: 'WEE',
  weeton: 'WET',
  'welham green': 'WMG',
  welling: 'WLI',
  wellingborough: 'WEL',
  'wellington (shropshire)': 'WLN',
  'wells next the sea': 'WEN',
  welshpool: 'WLP',
  'welwyn garden city': 'WGC',
  'welwyn north': 'WLW',
  wem: 'WEM',
  'wembley central': 'WMB',
  'wembley stadium': 'WCX',
  'wemyss bay': 'WMS',
  wendover: 'WND',
  wennington: 'WNN',
  'west allerton': 'WSA',
  'west brompton': 'WBP',
  'west byfleet': 'WBY',
  'west calder': 'WCL',
  'west croydon': 'WCY',
  'west drayton': 'WDT',
  'west dulwich': 'WDU',
  'west ealing': 'WEA',
  'west ham': 'WEH',
  'west hampstead': 'WHD',
  'west hampstead thameslink': 'WHP',
  'west horndon': 'WHR',
  'west kilbride': 'WKB',
  'west kirby': 'WKI',
  'west malling': 'WMA',
  'west norwood': 'WNW',
  'west ruislip': 'WRU',
  'west runton': 'WRN',
  'west st leonards': 'WLD',
  'west sutton': 'WSU',
  'west wickham': 'WWI',
  'west worthing': 'WWO',
  westbury: 'WSB',
  westcliff: 'WCF',
  'westcombe park': 'WCB',
  westenhanger: 'WHA',
  'wester hailes': 'WTA',
  westerfield: 'WFI',
  westerton: 'WES',
  'westgate-on-sea': 'WGA',
  westhoughton: 'WHG',
  'weston milton': 'WNM',
  'weston-super-mare': 'WSM',
  wetheral: 'WRL',
  weybridge: 'WYB',
  weymouth: 'WEY',
  'whaley bridge': 'WBR',
  whalley: 'WHE',
  whatstandwell: 'WTS',
  whifflet: 'WFF',
  whimple: 'WHM',
  whinhill: 'WNL',
  whiston: 'WHN',
  whitby: 'WTB',
  'whitchurch (cardiff)': 'WHT',
  'whitchurch (hampshire)': 'WCH',
  'whitchurch (shropshire)': 'WTC',
  'white hart lane': 'WHL',
  'white notley': 'WNY',
  whitechapel: 'ZLW',
  whitecraigs: 'WCR',
  whitehaven: 'WTH',
  whitland: 'WTL',
  'whitley bridge': 'WBD',
  'whitlocks end': 'WTE',
  whitstable: 'WHI',
  whittlesea: 'WLE',
  'whittlesford parkway': 'WLF',
  whitton: 'WTN',
  whitwell: 'WWL',
  'whyteleafe south': 'WHS',
  whyteleafe: 'WHY',
  wick: 'WCK',
  wickford: 'WIC',
  'wickham market': 'WCM',
  widdrington: 'WDD',
  widnes: 'WID',
  'widney manor': 'WMR',
  'wigan north western': 'WGN',
  'wigan wallgate': 'WGW',
  wigton: 'WGT',
  wildmill: 'WMI',
  'willesden junction': 'WIJ',
  williamwood: 'WLM',
  willington: 'WIL',
  wilmcote: 'WMC',
  wilmslow: 'WML',
  wilnecote: 'WNE',
  'wimbledon chase': 'WBO',
  wimbledon: 'WIM',
  winchelsea: 'WSE',
  winchester: 'WIN',
  winchfield: 'WNF',
  'winchmore hill': 'WIH',
  windermere: 'WDM',
  'windsor & eton central': 'WNC',
  'windsor & eton riverside': 'WNR',
  winnersh: 'WNS',
  'winnersh triangle': 'WTI',
  winsford: 'WSF',
  wishaw: 'WSH',
  witham: 'WTM',
  witley: 'WTY',
  witton: 'WTT',
  wivelsfield: 'WVF',
  wivenhoe: 'WIV',
  'woburn sands': 'WOB',
  woking: 'WOK',
  wokingham: 'WKM',
  woldingham: 'WOH',
  wolverhampton: 'WVH',
  wolverton: 'WOL',
  wombwell: 'WOM',
  'wood end': 'WDE',
  'wood street': 'WST',
  woodbridge: 'WDB',
  'woodgrange park': 'WGR',
  woodhall: 'WDL',
  woodhouse: 'WDH',
  woodlesford: 'WDS',
  woodley: 'WLY',
  woodmansterne: 'WME',
  woodsmoor: 'WSR',
  wool: 'WOO',
  woolston: 'WLS',
  woolwich: 'WWC',
  'woolwich arsenal': 'WWA',
  'woolwich dockyard': 'WWD',
  'wootton wawen': 'WWW',
  'worcester foregate street': 'WOF',
  'worcester park': 'WCP',
  'worcestershire parkway': 'WOP',
  'worcester shrub hill': 'WOS',
  workington: 'WKG',
  worksop: 'WRK',
  worle: 'WOR',
  worplesdon: 'WPL',
  worstead: 'WRT',
  worthing: 'WRH',
  wrabness: 'WRB',
  wraysbury: 'WRY',
  wrenbury: 'WRE',
  wressle: 'WRS',
  'wrexham central': 'WXC',
  'wrexham general': 'WRX',
  wye: 'WYE',
  wylam: 'WYM',
  'wylde green': 'WYL',
  wymondham: 'WMD',
  wythall: 'WYT',
  yalding: 'YAL',
  'yardley wood': 'YRD',
  yarm: 'YRM',
  'yarmouth (isle of wight)': 'YMH',
  yate: 'YAE',
  yatton: 'YAT',
  yeoford: 'YEO',
  'yeovil junction': 'YVJ',
  'yeovil pen mill': 'YVP',
  yetminster: 'YET',
  ynyswen: 'YNW',
  yoker: 'YOK',
  york: 'YRK',
  yorton: 'YRT',
  'ystrad mynach': 'YSM',
  'ystrad rhondda': 'YSR',
};

export default stations;
